import { spawnSync } from "node:child_process";
import { mkdir, readFile, writeFile } from "node:fs/promises";
import path from "node:path";

const role = process.env.AIOS_ROLE;
const task = process.env.AIOS_TASK_ID;
const cli = process.argv[2];
const root = process.cwd();
const planDirectory = path.join(root, "plans", "site-plan");

function taskDocument(id, title, objective, criterion) {
  return `---
schema: aios.task/v1
id: ${id}
project: test-project
title: ${title}
state: implement
retry:
  count: 0
  limit: 2
approval: not_required
last_review: null
---

# ${title}

## Objective

${objective}

## Acceptance Criteria

- ${criterion}

## Constraints

- Keep the work within one focused Worker session.

## Context

Generated by the website planning profile sandbox.

## Attempts

_None yet._
`;
}

async function materializePlan() {
  await mkdir(planDirectory, { recursive: true });
  await writeFile(
    path.join(planDirectory, "PLAN.md"),
    `---
schema: aios.plan/v1
id: site-plan
project: test-project
profile: website
profile_reason: The brief asks for a responsive two-page public website.
---

# Two-page website plan

## Brief

Build a responsive home page and about page with shared navigation.

## Profile Application

The website profile separates shared visual foundations from individual pages and finishes with observable responsive and accessibility criteria.

## Assumptions and Risks

The brief supplies final copy. Shared navigation is the main integration risk and is established first.

## Decomposition Rationale

Shared foundations come first so both page Tasks can use one navigation and visual language. Each page remains a one-session outcome.

## Execution Order

1. P-01 establishes the shared shell and design tokens.
2. P-02 builds the home page against that shell.
3. P-03 builds the about page and verifies cross-page navigation.
`,
    "utf8",
  );
  await writeFile(
    path.join(planDirectory, "P-01.md"),
    taskDocument(
      "P-01",
      "Build the shared website shell",
      "Create the shared navigation, layout shell, and visual tokens.",
      "The shared shell is responsive and keyboard navigable.",
    ),
    "utf8",
  );
  await writeFile(
    path.join(planDirectory, "P-02.md"),
    taskDocument(
      "P-02",
      "Build the home page",
      "Implement the home page content and primary call to action.",
      "The home page renders correctly at mobile and desktop widths.",
    ),
    "utf8",
  );
  await writeFile(
    path.join(planDirectory, "P-03.md"),
    taskDocument(
      "P-03",
      "Build the about page",
      "Implement the about page and complete cross-page navigation.",
      "Both pages are reachable through consistent accessible navigation.",
    ),
    "utf8",
  );
}

function checkPlan() {
  return spawnSync(
    process.execPath,
    [cli, "adopt", "plans/site-plan", "--root", root, "--check"],
    { cwd: root, encoding: "utf8", windowsHide: true },
  );
}

let result;
if (role === "implementer") {
  await materializePlan();
  const check = checkPlan();
  result =
    check.status === 0
      ? {
          schema: "aios.result/v1",
          task,
          role,
          status: "success",
          payload: {
            summary: "Created a website-profile plan with three focused proposals.",
            verification: "aios adopt --check passed for plans/site-plan.",
          },
        }
      : {
          schema: "aios.result/v1",
          task,
          role,
          status: "failure",
          payload: { reason: check.stderr || "plan validation failed" },
        };
} else if (role === "reviewer") {
  const check = checkPlan();
  const plan = await readFile(path.join(planDirectory, "PLAN.md"), "utf8");
  const coversBrief = /home page/i.test(plan) && /about page/i.test(plan);
  result = {
    schema: "aios.result/v1",
    task,
    role,
    status: "success",
    payload: {
      verdict: check.status === 0 && coversBrief ? "pass" : "changes_requested",
      findings:
        check.status === 0 && coversBrief
          ? "The website profile is justified, all proposals validate, and the two-page brief is covered at one-session granularity."
          : "The plan does not validate or does not cover both requested pages.",
    },
  };
} else {
  result = {
    schema: "aios.result/v1",
    task,
    role,
    status: "success",
    payload: { decision: "approved" },
  };
}

process.stdout.write(JSON.stringify(result));
